"""add recap_email_sent to tournament

Revision ID: 7f95f6308352
Revises: aba1c0314b71
Create Date: 2026-03-09 10:45:35.653655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f95f6308352'
down_revision = 'aba1c0314b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recap_email_sent', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('recap_email_sent')

    # ### end Alembic commands ###
