"""baseline: capture existing schema

Revision ID: aba1c0314b71
Revises: 
Create Date: 2026-03-04 15:32:35.644424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba1c0314b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pick_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pick_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('season_player_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_player_usage_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_player_usage_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tournament_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_field_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_field_tournament_id'), ['tournament_id'], unique=False)

    with op.batch_alter_table('tournament_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_result_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_result_tournament_id'), ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_result_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_result_player_id'))

    with op.batch_alter_table('tournament_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_field_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_field_player_id'))

    with op.batch_alter_table('season_player_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_player_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_season_player_usage_player_id'))

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pick_user_id'))
        batch_op.drop_index(batch_op.f('ix_pick_tournament_id'))

    # ### end Alembic commands ###
